services:
  roco-helper:
    image: h3110w0r1d6/roco-helper:latest
    container_name: roco-helper
    restart: unless-stopped
    environment:
      - ROCO_CAPTURE_MODE=socks5
      - ROCO_SOCKS5_BIND=0.0.0.0
      - ROCO_SOCKS5_PORT=1080
      - ROCO_BIND=0.0.0.0
      - ROCO_PORT=4939
      - ROCO_DATA_DIR=/data
    ports:
      - "4939:4939"
      - "1080:1080"
    volumes:
      - ./data:/data
