services:
  roco-helper:
    image: h3110w0r1d6/roco-helper:latest
    container_name: roco-helper
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - ROCO_CAPTURE_MODE=pcap
      - ROCO_IFACE=eth0
      - ROCO_BIND=0.0.0.0
      - ROCO_PORT=4939
      - ROCO_DATA_DIR=/data
    volumes:
      - ./data:/data
